package generate

import (
	"github.com/stretchr/testify/require"
	"github.com/terryhay/dolly/internal/generator/config_yaml"
	"github.com/terryhay/dolly/pkg/dollyconf"
	"testing"
)

func TestGenerate(t *testing.T) {
	t.Parallel()

	command := "cmd"
	additionalCommand := "addcmd"
	commandDescriptionHelpInfo := "command description help info"

	helpCommand := "help"
	additionalHelpCommand := "addhelp"

	requiredFlag1 := "-" + "-rf1"
	requiredFlag1Description := &config_yaml.FlagDescription{
		Flag: requiredFlag1,
		ArgumentsDescription: &config_yaml.ArgumentsDescription{
			AmountType: dollyconf.ArgAmountTypeSingle,
			DefaultValues: []string{
				"f1DefValue",
			},
			AllowedValues: []string{
				"f1AllValue",
			},
		},
	}

	requiredFlag2 := "-" + "-rf2"
	requiredFlag2Description := &config_yaml.FlagDescription{
		Flag: requiredFlag2,
		ArgumentsDescription: &config_yaml.ArgumentsDescription{
			AmountType: dollyconf.ArgAmountTypeList,
			DefaultValues: []string{
				"f2DefValue",
			},
			AllowedValues: []string{
				"f2AllValue",
			},
		},
	}

	optionalFlag1 := "-" + "-of1"
	optionalFlag1Description := &config_yaml.FlagDescription{
		Flag: optionalFlag1,
	}

	optionalFlag2 := "-" + "-of2"
	optionalFlag2Description := &config_yaml.FlagDescription{
		Flag: optionalFlag2,
	}

	config := &config_yaml.Config{
		AppHelpDescription: &config_yaml.AppHelpDescription{},
		HelpCommandDescription: &config_yaml.HelpCommandDescription{
			Command: helpCommand,
			AdditionalCommands: []string{
				additionalHelpCommand,
			},
		},
		NamelessCommandDescription: &config_yaml.NamelessCommandDescription{
			ArgumentsDescription: &config_yaml.ArgumentsDescription{},
			RequiredFlags: []string{
				requiredFlag1,
				requiredFlag2,
			},
			OptionalFlags: []string{
				optionalFlag1,
				optionalFlag2,
			},
		},
		CommandDescriptions: []*config_yaml.CommandDescription{
			{
				Command: command,
				AdditionalCommands: []string{
					additionalCommand,
				},
				DescriptionHelpInfo: commandDescriptionHelpInfo,
				ArgumentsDescription: &config_yaml.ArgumentsDescription{
					AmountType: dollyconf.ArgAmountTypeSingle,
					DefaultValues: []string{
						"cmdDefValue",
					},
					AllowedValues: []string{
						"cmdAllValue",
					},
				},
				RequiredFlags: []string{
					requiredFlag1,
					requiredFlag2,
				},
				OptionalFlags: []string{
					optionalFlag1,
					optionalFlag2,
				},
			},
			{
				// fake empty command
				ArgumentsDescription: &config_yaml.ArgumentsDescription{
					AmountType: dollyconf.ArgAmountTypeList,
					DefaultValues: []string{
						"fakeEmptyCommandDefValue",
					},
					AllowedValues: []string{
						"fakeEmptyCommandAllValue",
					},
				},
			},
		},
		FlagDescriptions: []*config_yaml.FlagDescription{
			requiredFlag1Description,
			requiredFlag2Description,
			optionalFlag1Description,
			optionalFlag2Description,
		},
	}

	argParserFileText := Generate(
		config,
		map[string]*config_yaml.FlagDescription{
			requiredFlag1: requiredFlag1Description,
			requiredFlag2: requiredFlag2Description,
			optionalFlag1: optionalFlag1Description,
			optionalFlag2: optionalFlag2Description,
		})

	expectedArgParserFileText := `// This code was generated by dolly.generator. DO NOT EDIT

package dolly

import (
	"github.com/terryhay/dolly/pkg/dollyconf"
	"github.com/terryhay/dolly/pkg/dollyerr"
	"github.com/terryhay/dolly/pkg/helpdisplay/data"
	tbd "github.com/terryhay/dolly/pkg/helpdisplay/termbox_decorator"
	"github.com/terryhay/dolly/pkg/helpdisplay/views"
	"github.com/terryhay/dolly/pkg/parsed_data"
	"github.com/terryhay/dolly/pkg/parser"
)

const (
	// CommandIDNamelessCommand - 
	CommandIDNamelessCommand dollyconf.CommandID = iota + 1
	//  - 
	
	// CommandIDCmd - command description help info
	CommandIDCmd
	// CommandIDPrintHelpInfo - print help info
	CommandIDPrintHelpInfo
)

const (
	//  - 
	 dollyconf.Command = ""
	// CommandAddcmd - command description help info
	CommandAddcmd = "addcmd"
	// CommandAddhelp - print help info
	CommandAddhelp = "addhelp"
	// CommandCmd - command description help info
	CommandCmd = "cmd"
	// CommandHelp - print help info
	CommandHelp = "help"
)

const (
	// FlagOf1 - 
	FlagOf1 dollyconf.Flag = "--of1"
	// FlagOf2 - 
	FlagOf2 = "--of2"
	// FlagRf1 - 
	FlagRf1 = "--rf1"
	// FlagRf2 - 
	FlagRf2 = "--rf2"
)

// Parse - processes command line arguments
func Parse(args []string) (res *parsed_data.ParsedData, err *dollyerr.Error) {
	appArgConfig := dollyconf.NewArgParserConfig(
		// appDescription
		dollyconf.ApplicationDescription{
			AppName: "",
			NameHelpInfo: "",
			DescriptionHelpInfo: nil,
		},
		// flagDescriptions
		map[dollyconf.Flag]*dollyconf.FlagDescription{
			FlagRf1: {
				DescriptionHelpInfo:  "",
				ArgDescription: &dollyconf.ArgumentsDescription{
					AmountType:              dollyconf.ArgAmountTypeSingle,
					SynopsisHelpDescription: "",
					DefaultValues: []string{
						"f1DefValue",
					},
					AllowedValues: map[string]bool{
						"f1AllValue": true,
					},
				},
			},
			FlagRf2: {
				DescriptionHelpInfo:  "",
				ArgDescription: &dollyconf.ArgumentsDescription{
					AmountType:              dollyconf.ArgAmountTypeList,
					SynopsisHelpDescription: "",
					DefaultValues: []string{
						"f2DefValue",
					},
					AllowedValues: map[string]bool{
						"f2AllValue": true,
					},
				},
			},
			FlagOf1: {
				DescriptionHelpInfo:  "",
			},
			FlagOf2: {
				DescriptionHelpInfo:  "",
			},
		},
		// commandDescriptions
		[]*dollyconf.CommandDescription{
			{
				ID:                  CommandIDCmd,
				DescriptionHelpInfo: "command description help info",
				Commands: map[dollyconf.Command]bool{
					CommandCmd: true,
					CommandAddcmd: true,
				},
				RequiredFlags: map[dollyconf.Flag]bool{
					FlagRf1: true,
					FlagRf2: true,
				},
				OptionalFlags: map[dollyconf.Flag]bool{
					FlagOf1: true,
					FlagOf2: true,
				},
			},
			{
				ID:                  ,
				DescriptionHelpInfo: "",
				Commands: map[dollyconf.Command]bool{
					: true,
				},
			},
		},
		// helpCommandDescription
		dollyconf.NewHelpCommandDescription(
			CommandIDPrintHelpInfo,
			map[dollyconf.Command]bool{
				CommandAddhelp: true,
				CommandHelp: true,
			},
		),
		// namelessCommandDescription
		dollyconf.NewNamelessCommandDescription(
			CommandIDNamelessCommand,
			"",
			&dollyconf.ArgumentsDescription{
				AmountType:              dollyconf.ArgAmountTypeNoArgs,
				SynopsisHelpDescription: "",
			},
			map[dollyconf.Flag]bool{
				FlagRf1: true,
				FlagRf2: true,
			},
			map[dollyconf.Flag]bool{
				FlagOf1: true,
				FlagOf2: true,
			},
		))

	if res, err = parser.Parse(appArgConfig, args); err != nil {
		return nil, err
	}

	if res.GetCommandID() == CommandIDPrintHelpInfo {
		var pageView views.PageView
		err = pageView.Init(tbd.NewTermBoxDecorator(nil), data.MakePage(appArgConfig))
		if err != nil {
			return nil, err
		}
		err = pageView.Run()
		if err != nil {
			return nil, err
		}

		return nil, nil
	}

	return res, nil
}
`
	require.Equal(t, expectedArgParserFileText, argParserFileText)
}

func TestGenerateWithoutNamelessCommand(t *testing.T) {
	t.Parallel()

	descriptionHelpInfo := "command description help info"

	helpCommand := "help"
	additionalHelpCommand := "addhelp"

	argParserFileText := Generate(
		&config_yaml.Config{
			AppHelpDescription: &config_yaml.AppHelpDescription{
				DescriptionHelpInfo: []string{
					descriptionHelpInfo,
				},
			},
			HelpCommandDescription: &config_yaml.HelpCommandDescription{
				Command: helpCommand,
				AdditionalCommands: []string{
					additionalHelpCommand,
				},
			},
		},
		nil)

	require.Equal(t, `// This code was generated by dolly.generator. DO NOT EDIT

package dolly

import (
	"github.com/terryhay/dolly/pkg/dollyconf"
	"github.com/terryhay/dolly/pkg/dollyerr"
	"github.com/terryhay/dolly/pkg/helpdisplay/data"
	tbd "github.com/terryhay/dolly/pkg/helpdisplay/termbox_decorator"
	"github.com/terryhay/dolly/pkg/helpdisplay/views"
	"github.com/terryhay/dolly/pkg/parsed_data"
	"github.com/terryhay/dolly/pkg/parser"
)

const (
	// CommandIDPrintHelpInfo - print help info
	CommandIDPrintHelpInfo dollyconf.CommandID = iota + 1
)

const (
	// CommandAddhelp - print help info
	CommandAddhelp dollyconf.Command = "addhelp"
	// CommandHelp - print help info
	CommandHelp = "help"
)


// Parse - processes command line arguments
func Parse(args []string) (res *parsed_data.ParsedData, err *dollyerr.Error) {
	appArgConfig := dollyconf.NewArgParserConfig(
		// appDescription
		dollyconf.ApplicationDescription{
			AppName: "",
			NameHelpInfo: "",
			DescriptionHelpInfo: []string{
				"command description help info",
			},
		},
		// flagDescriptions
		nil,
		// commandDescriptions
		nil,
		// helpCommandDescription
		dollyconf.NewHelpCommandDescription(
			CommandIDPrintHelpInfo,
			map[dollyconf.Command]bool{
				CommandAddhelp: true,
				CommandHelp: true,
			},
		),
		// namelessCommandDescription
		nil)

	if res, err = parser.Parse(appArgConfig, args); err != nil {
		return nil, err
	}

	if res.GetCommandID() == CommandIDPrintHelpInfo {
		var pageView views.PageView
		err = pageView.Init(tbd.NewTermBoxDecorator(nil), data.MakePage(appArgConfig))
		if err != nil {
			return nil, err
		}
		err = pageView.Run()
		if err != nil {
			return nil, err
		}

		return nil, nil
	}

	return res, nil
}
`, argParserFileText)
}

func TestGenerateWithoutHelpCommandDescription(t *testing.T) {
	t.Parallel()

	argParserFileText := Generate(
		&config_yaml.Config{
			AppHelpDescription: &config_yaml.AppHelpDescription{
				DescriptionHelpInfo: []string{
					"command description help info",
				},
			},
			NamelessCommandDescription: &config_yaml.NamelessCommandDescription{
				DescriptionHelpInfo: "nameless command description help info",
			},
		},
		nil)

	require.Equal(t, `// This code was generated by dolly.generator. DO NOT EDIT

package dolly

import (
	"github.com/terryhay/dolly/pkg/dollyconf"
	"github.com/terryhay/dolly/pkg/dollyerr"
	"github.com/terryhay/dolly/pkg/helpdisplay/data"
	tbd "github.com/terryhay/dolly/pkg/helpdisplay/termbox_decorator"
	"github.com/terryhay/dolly/pkg/helpdisplay/views"
	"github.com/terryhay/dolly/pkg/parsed_data"
	"github.com/terryhay/dolly/pkg/parser"
)

const (
	// CommandIDNamelessCommand - nameless command description help info
	CommandIDNamelessCommand dollyconf.CommandID = iota + 1
)



// Parse - processes command line arguments
func Parse(args []string) (res *parsed_data.ParsedData, err *dollyerr.Error) {
	appArgConfig := dollyconf.NewArgParserConfig(
		// appDescription
		dollyconf.ApplicationDescription{
			AppName: "",
			NameHelpInfo: "",
			DescriptionHelpInfo: []string{
				"command description help info",
			},
		},
		// flagDescriptions
		nil,
		// commandDescriptions
		nil,
		// helpCommandDescription
		nil,
		// namelessCommandDescription
		dollyconf.NewNamelessCommandDescription(
			CommandIDNamelessCommand,
			"nameless command description help info",
			 nil,
			nil,
			nil,
		))

	if res, err = parser.Parse(appArgConfig, args); err != nil {
		return nil, err
	}

	if res.GetCommandID() ==  {
		var pageView views.PageView
		err = pageView.Init(tbd.NewTermBoxDecorator(nil), data.MakePage(appArgConfig))
		if err != nil {
			return nil, err
		}
		err = pageView.Run()
		if err != nil {
			return nil, err
		}

		return nil, nil
	}

	return res, nil
}
`, argParserFileText)
}

func TestNilInputData(t *testing.T) {
	t.Parallel()

	argParserFileText := Generate(nil, nil)

	require.Equal(t, `// This code was generated by dolly.generator. DO NOT EDIT

package dolly

import (
	"github.com/terryhay/dolly/pkg/dollyconf"
	"github.com/terryhay/dolly/pkg/dollyerr"
	"github.com/terryhay/dolly/pkg/helpdisplay/data"
	tbd "github.com/terryhay/dolly/pkg/helpdisplay/termbox_decorator"
	"github.com/terryhay/dolly/pkg/helpdisplay/views"
	"github.com/terryhay/dolly/pkg/parsed_data"
	"github.com/terryhay/dolly/pkg/parser"
)




// Parse - processes command line arguments
func Parse(args []string) (res *parsed_data.ParsedData, err *dollyerr.Error) {
	appArgConfig := dollyconf.NewArgParserConfig(
		// appDescription
		dollyconf.ApplicationDescription{
			AppName: "",
			NameHelpInfo: "",
			DescriptionHelpInfo: nil,
		},
		// flagDescriptions
		nil,
		// commandDescriptions
		nil,
		// helpCommandDescription
		nil,
		// namelessCommandDescription
		nil)

	if res, err = parser.Parse(appArgConfig, args); err != nil {
		return nil, err
	}

	if res.GetCommandID() ==  {
		var pageView views.PageView
		err = pageView.Init(tbd.NewTermBoxDecorator(nil), data.MakePage(appArgConfig))
		if err != nil {
			return nil, err
		}
		err = pageView.Run()
		if err != nil {
			return nil, err
		}

		return nil, nil
	}

	return res, nil
}
`, argParserFileText)
}
