# required
version: 1.0.0

# required
arg_parser:

  # required
  app_help:
    # required fields:
    app_name: "example3"
    chapter_name_info: "shows how parser generator works without commands and flags"
    chapter_description_info:
      - "you can write more detailed description here"

  # required if this is no command_descriptions
  nameless_command:
    # required
    chapter_description_info: "runs example3"

  # required
  help_command:
    main_name: "help"
    # optional fields
    additional_names:
      - "-h"


