# required
version: 1.0.0

# required
arg_parser:

  # required
  app_help:
    # required fields:
    app_name: "grep"
    chapter_name_info: "file pattern searcher"
    chapter_description_info:
      - "The grep utility searches any given input files, selecting lines that match one or more patterns.  By default, apattern matches an input line if the regular expression (RE) in the pattern matches the input line without its trailing newline.  An empty expression matches every line.  Each input line that matches at least one of the patterns is written to the standard output."
      - "grep is used for simple patterns and basic regular expressions (BREs); egrep can handle extended regular expressions (EREs).  See re_format(7) for more information on regular expressions.  fgrep is quicker than both grep and egrep, but can only handle fixed patterns (i.e., it does not interpret regular expressions).  Patterns may consist of one or more lines, allowing any of the pattern lines to match a portion of the input."
      - "zgrep, zegrep, and zfgrep act like grep, egrep, and fgrep, respectively, but accept input files compressed with the compress(1) or gzip(1) compression utilities.  bzgrep, bzegrep, and bzfgrep act like grep, egrep, and fgrep, respectively, but accept input files compressed with the bzip2(1) compression utility."

  # optional
  placeholders:
    - flag: &flagAUppercase "-A"
      additional_flags:
        - "--after-context"
      chapter_description_info: "Print num lines of trailing context after each match.  See also the -B and -C options."
      # optional fields
      arg:
        # required fields
        amount_type: "single"
        synopsis_description: "num"

    - flag: &flagALowercase "-a"
      chapter_description_info: "Treat all files as ASCII text.  Normally grep will simply print “Binary file ... matches” if files contain binary characters.  Use of this option forces grep to output lines matching the specified pattern."

    - flag: &flagBUppercase "-B"
      chapter_description_info: "Print num lines of leading context before each match.  See also the -A and -C options."
      # optional fields
      arg:
        # required fields
        amount_type: "single"
        synopsis_description: "num"

    - flag: &flagBLowercase "-b"
      chapter_description_info: "The offset in bytes of a matched pattern is displayed in front of the respective matched line."

    - flag: &flagCUppercase "-C"
      chapter_description_info: "Print num lines of leading and trailing context surrounding each match.  The default value of num is “2” and is equivalent to “-A 2 -B 2”.  Note: no whitespace may be given between the option and its argument."
      # optional fields
      arg:
        # required fields
        amount_type: "single"
        synopsis_description: "num"

    - flag: &flagCLowercase "-c"
      chapter_description_info: "Only a count of selected lines is written to standard output."


  # optional
  nameless_command:
    # required
    chapter_description_info: "checks arguments types"
    optional_flags:
      - *flagAUppercase
      - *flagALowercase
      - *flagBUppercase
      - *flagBLowercase
      - *flagCUppercase
      - *flagCLowercase

  # required
  help_command:
    main_name: "help"
    # optional fields
    additional_names:
      - "-h"

help_out_config:
  using_tool: "man_style"