# required
version: 1.0.0

# required
arg_parser:

  # required
  app_help:
    # required fields:
    app_name: "example2"
    chapter_name_info: "shows how parser generator works without commands"
    chapter_description_info:
      - "you can write more detailed description here"

  # required
  help_command:
    main_name: "help"
    # optional fields
    additional_names:
      - "-h"

  # optional
  placeholders:
    - flag: &checkCommandArguments "-check"
      chapter_description_info: "check command arguments types"
      # optional fields
      arg:
        # required fields
        amount_type: "single"
        synopsis_description: "str"
        # optional fields:
        arg:
          amount_type: "single"
          synopsis_description: "log level"
          default_values:
            - "s"
          allowed_values:
            - "s"
            - "i"
            - "f"

  # required if this is no command_descriptions
  nameless_command:
    # required
    chapter_description_info: "checks arguments types"
    # optional fields
    args:
      # required fields
      amount_type: "list"
      synopsis_description: "str list"
    required_flags:
      - *checkCommandArguments

