// This code was generated by dolly.generator. DO NOT EDIT

package dolly

import (
	apConf "github.com/terryhay/dolly/argparser/arg_parser_config"
	"github.com/terryhay/dolly/argparser/parsed_data"
	"github.com/terryhay/dolly/argparser/parser"
	helpOut "github.com/terryhay/dolly/argparser/plain_help_out"
	"github.com/terryhay/dolly/utils/dollyerr"
)

const (
	// CommandIDNamelessCommand - checks arguments types
	CommandIDNamelessCommand apConf.CommandID = iota + 1
	// CommandIDPrintHelpInfo - print help info
	CommandIDPrintHelpInfo
	// CommandIDPrint - print command line arguments with optional checking
	CommandIDPrint
)

const (
	// CommandH - print help info
	CommandH apConf.Command = "-h"
	// CommandHelp - print help info
	CommandHelp = "help"
	// CommandPrint - print command line arguments with optional checking
	CommandPrint = "print"
)

const (
	// FlagCheckargs - do arguments checking
	FlagCheckargs apConf.Flag = "-checkargs"
	// FlagF - single float
	FlagF = "-f"
	// FlagFl - float list
	FlagFl = "-fl"
	// FlagI - int string
	FlagI = "-i"
	// FlagIl - int list
	FlagIl = "-il"
	// FlagS - single string
	FlagS = "-s"
	// FlagSl - string list
	FlagSl = "-sl"
)

// Parse - processes command line arguments
func Parse(args []string) (res *parsed_data.ParsedData, err *dollyerr.Error) {
	appArgConfig := apConf.NewArgParserConfig(
		// appDescription
		apConf.ApplicationDescription{
			AppName:      "example",
			NameHelpInfo: "shows how parser generator works",
			DescriptionHelpInfo: []string{
				"you can write more detailed description here",
				"and use several paragraphs",
			},
		},
		// flagDescriptions
		map[apConf.Flag]*apConf.FlagDescription{
			FlagS: {
				DescriptionHelpInfo: "single string",
				ArgDescription: &apConf.ArgumentsDescription{
					AmountType:              apConf.ArgAmountTypeSingle,
					SynopsisHelpDescription: "str",
				},
			},
			FlagSl: {
				DescriptionHelpInfo: "string list",
				ArgDescription: &apConf.ArgumentsDescription{
					AmountType:              apConf.ArgAmountTypeList,
					SynopsisHelpDescription: "str",
				},
			},
			FlagI: {
				DescriptionHelpInfo: "int string",
				ArgDescription: &apConf.ArgumentsDescription{
					AmountType:              apConf.ArgAmountTypeSingle,
					SynopsisHelpDescription: "str",
				},
			},
			FlagIl: {
				DescriptionHelpInfo: "int list",
				ArgDescription: &apConf.ArgumentsDescription{
					AmountType:              apConf.ArgAmountTypeList,
					SynopsisHelpDescription: "str",
				},
			},
			FlagF: {
				DescriptionHelpInfo: "single float",
				ArgDescription: &apConf.ArgumentsDescription{
					AmountType:              apConf.ArgAmountTypeSingle,
					SynopsisHelpDescription: "str",
				},
			},
			FlagFl: {
				DescriptionHelpInfo: "float list",
				ArgDescription: &apConf.ArgumentsDescription{
					AmountType:              apConf.ArgAmountTypeList,
					SynopsisHelpDescription: "str",
				},
			},
			FlagCheckargs: {
				DescriptionHelpInfo: "do arguments checking",
			},
		},
		// commandDescriptions
		[]*apConf.CommandDescription{
			{
				ID:                  CommandIDPrint,
				DescriptionHelpInfo: "print command line arguments with optional checking",
				Commands: map[apConf.Command]bool{
					CommandPrint: true,
				},
				OptionalFlags: map[apConf.Flag]bool{
					FlagS:         true,
					FlagSl:        true,
					FlagI:         true,
					FlagIl:        true,
					FlagF:         true,
					FlagFl:        true,
					FlagCheckargs: true,
				},
			},
		},
		// helpCommandDescription
		apConf.NewHelpCommandDescription(
			CommandIDPrintHelpInfo,
			map[apConf.Command]bool{
				CommandH:    true,
				CommandHelp: true,
			},
		),
		// namelessCommandDescription
		apConf.NewNamelessCommandDescription(
			CommandIDNamelessCommand,
			"checks arguments types",
			nil,
			nil,
			map[apConf.Flag]bool{
				FlagSl: true,
				FlagIl: true,
				FlagFl: true,
			},
		))

	if res, err = parser.Parse(appArgConfig, args); err != nil {
		return nil, err
	}

	if res.GetCommandID() == CommandIDPrintHelpInfo {
		helpOut.PrintHelpInfo(appArgConfig)
		return nil, nil
	}

	return res, nil
}
