package generate

import (
	"fmt"
)

const templateArgParserFileBody = `// This code was generated by dolly.generator. DO NOT EDIT

package dolly

%s
%s
%s
%s

// Parse - processes command line arguments
func Parse(args []string) (res *parsed_data.ParsedData, err *dollyerr.Error) {
	appArgConfig := apConf.NewArgParserConfig(%s,%s,%s,%s,%s)

	if res, err = parser.Parse(appArgConfig, args); err != nil {
		return nil, err
	}

	if res.GetCommandID() == %s {%s
	}

	return res, nil
}
`

// GenArgParserFileBody applies page to argParserFileTemplate
func GenArgParserFileBody(
	importSection importSection,
	commandIDListSection sectionCommandIDList,
	commandNameIDListSection sectionCommandList,
	flagStringIDListSection sectionFlagStringIDList,
	appDescriptionSection sectionAppDescription,
	flagDescriptionsSection sectionFlagDescriptions,
	commandDescriptionsSection sectionCommandDescriptions,
	helpCommandDescriptionSection sectionHelpCommandDescription,
	namelessCommandDescriptionSection NamelessCommandDescriptionSection,
	helpCommandID string,
	helpOutSection helpOutSection,
) string {

	return fmt.Sprintf(
		templateArgParserFileBody,

		importSection,

		commandIDListSection,
		commandNameIDListSection,
		flagStringIDListSection,

		appDescriptionSection,
		flagDescriptionsSection,
		commandDescriptionsSection,
		helpCommandDescriptionSection,
		namelessCommandDescriptionSection,

		helpCommandID,
		helpOutSection,
	)
}
