package generate

import (
	"fmt"
)

const templateArgParserFileBody = `// This code was generated by dolly.generator. DO NOT EDIT

package dolly

%s
%s
%s
%s

// Parse - processes command line arguments
func Parse(args []string) (*parsed.ParsedData, error) {
	appArgConfig := apConf.ArgParserConfigSrc{%s,%s,%s,%s,%s}.ToConst()

	res, err := parser.Parse(appArgConfig, args)
	if err != nil {
		return nil, err.Error()
	}

	if res.GetCommandID() == %s {%s
	}

	return res, nil
}
`

// GenArgParserFileBody applies page to argParserFileTemplate
func GenArgParserFileBody(
	importSection importSection,
	commandIDListSection sectionCommandIDList,
	commandNameIDListSection sectionCommandList,
	flagStringIDListSection sectionFlagStringIDList,
	appDescriptionSection sectionAppDescription,
	flagDescriptionsSection sectionFlagDescriptions,
	commandDescriptionsSection sectionCommandDescriptions,
	helpCommandDescriptionSection sectionHelpCommandDescription,
	namelessCommandDescriptionSection NamelessCommandDescriptionSection,
	helpCommandID string,
	helpOutSection helpOutSection,
) string {
	return fmt.Sprintf(
		templateArgParserFileBody,

		importSection,

		commandIDListSection,
		commandNameIDListSection,
		flagStringIDListSection,

		appDescriptionSection,
		flagDescriptionsSection,
		commandDescriptionsSection,
		helpCommandDescriptionSection,
		namelessCommandDescriptionSection,

		helpCommandID,
		helpOutSection,
	)
}
