// This code was generated by dolly.generator. DO NOT EDIT

package dolly

import (
	"github.com/terryhay/dolly/argparser/parsed"
	coty "github.com/terryhay/dolly/tools/common_types"
)

const (
	// CommandHLw - print help info
	CommandHLw coty.NameCommand = "-h"
	// CommandHelp - print help info
	CommandHelp = "help"
)

const (
	// FlagCheck - check command arguments types
	FlagCheck coty.NameFlag = "-check"
)

// Parse - processes command line arguments
func Parse(args []string) (*parsed.Result, error) {

	return nil, nil
}
