# required
version: 1.0.0

# required
arg_parser_config:

  # required
  app_help_description:
    # required fields:
    app_name: "example"
    name_help_info: "shows how parser generator works"
    description_help_info:
      - "you can write more detailed description here"
      - "and use several paragraphs"

  # required
  help_command_description:
    command: "help"
    # optional fields
    additional_commands:
      - "-h"

  # optional
  flag_descriptions:
    - flag: &flagStringSingle "-s"
      description_help_info: "single string"
      # optional fields
      arguments_description:
        # required fields
        amount_type: "single"
        synopsis_description: "str"

    - flag: &flagStringList "-sl"
      description_help_info: "string list"
      # optional fields
      arguments_description:
        # required fields
        amount_type: "list"
        synopsis_description: "str"

    - flag: &flagIntSingle "-i"
      description_help_info: "int string"
      # optional fields
      arguments_description:
        # required fields
        amount_type: "single"
        synopsis_description: "str"

    - flag: &flagIntList "-il"
      description_help_info: "int list"
      # optional fields
      arguments_description:
        # required fields
        amount_type: "list"
        synopsis_description: "str"

    - flag: &flagFloatSingle "-f"
      description_help_info: "single float"
      # optional fields
      arguments_description:
        # required fields
        amount_type: "single"
        synopsis_description: "str"

    - flag: &flagFloatList "-fl"
      description_help_info: "float list"
      # optional fields
      arguments_description:
        # required fields
        amount_type: "list"
        synopsis_description: "str"

    - flag: &doTypeCheckingFlag "-checkargs"
      description_help_info: "do arguments checking"

  # optional
  nameless_command_description:
    # required
    description_help_info: "checks arguments types"
    optional_flags:
      - *flagStringList
      - *flagIntList
      - *flagFloatList

  # optional
  command_descriptions:
    - command: "print"
      description_help_info: "print command line arguments with optional checking"
      # optional fields
      arguments_description:
        amount_type: "list"
        synopsis_description: "value"
      optional_flags:
        - *flagStringSingle
        - *flagStringList
        - *flagIntSingle
        - *flagIntList
        - *flagFloatSingle
        - *flagFloatList
        - *doTypeCheckingFlag

help_out_config:
  using_tool: "man_style"
